# Generated by Django 2.0 on 2018-11-21 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0006_auto_20181122_0128'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_login_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
