# Generated by Django 2.0 on 2018-11-21 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0008_auto_20181122_0257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='linkedin',
            new_name='linkedIn',
        ),
    ]
