# Generated by Django 2.0 on 2018-11-23 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0009_auto_20181122_0317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='linkedIn',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_pic',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='twitter',
        ),
    ]
