# Generated by Django 2.0 on 2018-11-23 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0013_remove_userprofile_user_badge_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='image',
        ),
    ]
