# Generated by Django 2.0 on 2018-11-21 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0004_auto_20181121_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email_activated',
        ),
    ]
