# Generated by Django 2.0 on 2018-11-21 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0005_remove_userprofile_email_activated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='events_registered',
            field=models.ManyToManyField(blank=True, related_name='regEvents', to='userprofiles.Event'),
        ),
    ]
