# Generated by Django 2.0 on 2018-11-23 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0011_userprofile_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user_badge_icon',
        ),
    ]
